name: run main2.py

on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # Updated to latest version

      - name: Update and Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install chromium-driver  # Install Chromium Driver apt-get install chromium-driver

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Install required Python version
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        run: python main2.py
