name: run main2.py

on:
  workflow_dispatch:  # Allows manual trigger

  schedule:
    - cron: '30 7 * * *' # Runs every day @1PM IST

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: checkout repo content
        uses: actions/checkout@v4 # Updated to latest version
        with:
          persist-credentials: false

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # Install required Python version
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN}}
          CHAT_ID: ${{ secrets.CHAT_ID}}
        run: python main2.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
